#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# path_to_file="$1"
# ip="$2"
# username="$3"
# path_ssh_key="$4"

if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
