#!/usr/bin/env bash
# Install and configure HAproxy (load balancer)
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 2525-web-01 35.196.52.46:80 check
    server 2525-web-02 18.232.176.193:80 check
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
