#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
I=1
while [ $I -le 10 ]; do
        if [ $I == 4 ]; then
                echo "bad luck"
        elif [ $I == 8 ]; then
                echo "good luck"
        else
                echo "Holberton School"
        fi
        ((I++))
done
