#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
I=1
while [ $I -le 20 ]; do
	echo $I
	if [ $I == 4 ]; then
		echo "bad luck from China"
	elif [ $I == 9 ]; then
		echo "bad luck from Japan"
	elif [ $I == 17 ]; then
		echo "bad luck from Italy"
	fi
	((I++))
done
