#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
LIST=$(find -- * -maxdepth 1| cut -d'-' -f2-)
for i in $LIST; do
        echo "$i"
done
